### ISSUE TITLE
Module doesn't honor the configured number of values of the imagefield 

### ISSUE THREAD

**Issue by a8w4** [BWPanda/pdf_to_image#2]
instead it creates all pages of a multi-paged PDF as images regardless of the configuration of the imagefield.

**Comment by olafgrabienski** [comment]
@a8w4 Many thanks for your report! I've heard the module maintainer is quite busy at the moment, so I thought I'd have a look at it. I've tried to reproduce the issue, so far without luck. In my test, the module creates only the number of PDF pages which is configured as maximum number in the image field configuration, as expected. My configuration steps in a vanilla Backdrop site:

1. Install *PDF to Image*.
2. Go to the *Post* content type, configure the *Image* field, and allow a maximum of two images.
3. Add a file field to the content type, in section "PDF to image" set *Image* as the image field, and leave the other settings untouched.
4. Add a *Post* item, upload a PDF file with more than two pages, and save the post.

Result: The post displays two images, as expected.

Can you confirm my findings on a fresh Backdrop site?

**Comment by a8w4** [comment]
Thank you for stepping in! Please look in the files directory and watch out for the number of files after each upload - it creates image files for each page of the PDF regardless of the set limitation of the image field - that was the problem I ran into. 
Also please configure a file path (a subdirectory of files) for the image field - you will notice, that the image files are created still in the root of the files directory.

**Comment by olafgrabienski** [comment]
> Please look in the files directory and watch out for the number of files after each upload - it creates image files for each page of the PDF regardless of the set limitation of the image field - that was the problem I ran into.

Thanks for the update! I've had a quick look at the files directory and can confirm there are many files. Will have a closer look soon.

**Comment by olafgrabienski** [comment]
@a8w4 I've had another look, you're right:

- Uploading a PDF to a post creates an image file for each page of the PDF, regardless of the image field limitation. (The post itself displays the expected number of images.)
- The image files end up in the `files` directory, even if there is a specific file path for the image field.

After applying the [pull request](https://github.com/backdrop-contrib/pdf_to_image/pull/1) to my test site, uploading a PDF created exactly the expected number of images (according to the image field limitation), and the images weren't saved in the `files`directory but in the configured subdirectory.

However, to make this working, I had to create the subdirectory for the image path manually. Before that, I got messages like this one:

> File temporary://fileNKNJJV could not be moved/copied because the destination directory public://field/image is not configured correctly.

In contrast, uploading an image directly to the image field, the same image path worked fine, i.e. Backdrop was able to create the subdirectory without any problem.

**Comment by a8w4** [comment]
@olafgrabienski Hey, that's great - thank you for your evaluation - and thank you for catching this new bug, I presumed that the subdirectory would be created by the config-submit handler of the image field, but did not test explicitly, because when I came up with my solution, the directory was already created.... everything seemed to work fine...
I will add the creation part to this module and update my pull request afterwards.

**Comment by a8w4** [comment]
@olafgrabienski now the fix is fixed - I just pushed the new version of #1 - what do you think?

**Comment by olafgrabienski** [comment]
Great, thank you! On my test site, I've deleted the former used test directories, updated the PR with the fix, and uploaded a new multi-page PDF. Everything worked as expected. Especially, this time the subdirectory for the image path was created without any problem. So, the PR works for me!

**Comment by olafgrabienski** [comment]
@a8w4 Some more suggestions:

- Please put a link to your PR in the issue description (first comment) and/or copy the following line to your PR description:
  `Fixes https://github.com/backdrop-contrib/pdf_to_image/issues/2.` The latter will provide an automatic Github link to show the 'fixing' PR on the issue.
- I've left a small comment at the PR about coding standards.

**Comment by olafgrabienski** [comment]
As said above, the PR works for me. Thanks again! As I don't have the skills, we need someone else to make a code review and hopefully merge the PR. @BWPanda or @backdrop-contrib/bug-squad - are you up to have a look at the PR?

**Comment by ghost** [comment]
I will review when I get a chance.

**Comment by ghost** [comment]
For the record @olafgrabienski, the Bug Squad only get involved to merge PRs once the PR has been in an RTBC state for at least 2 weeks. See https://backdropcms.org/leadership/bug-squad

**Comment by olafgrabienski** [comment]
Thanks for the hint, @BWPanda! I didn't have the exact procedures in mind. Reading that page I see however that the bug squad tries "to take the burden of project maintainership" and feels also responsible to review pull requests "for eligibility". I thought something like that would be helpful in case you weren't available.

**Comment by jenlampton** [comment]
In this case, "review  for eligibility" only means "see if the PR has been in an RTBC state for at least 2 weeks". 

However, since I'm here, I've done a quick code review and the PR looks great. There are some unrelated code changes in there, but all seem like good improvements, and more likely to avoid issues than cause them. 

> As said above, the PR works for me.

@olafgrabienski since you have manually tested the PR and it works for you, I'd say this issue is RTBC.

**Comment by ghost** [comment]
Thanks for your work on this @a8w4. I've reviewed the PR and requested some changes.

I think a few things should be split off into separate issues for better discussion, and one of the changes you made was unnecessary and needs to be removed.

I've also marked this issue as a feature request since I don't believe it is a bug per se; just that it works differently to how some might expect it to behind the scenes (it certainly works as expected from the users point of view).

**Comment by olafgrabienski** [comment]
@jenlampton @BWPanda Thanks for your input!

I'm not able to evaluate code related questions but I'll be happy to test the PR again when it's ready.

**Comment by a8w4** [comment]
@BWPanda Sorry, I really have to disagree about this issue not being a bug report: just imagine the PDF is an ebook of 320 pages and you wanted only the title page extracted. For 320 pages the module would create image files of which 319 would be unused and superfluous cluttering the directory. It also may very well run into a timeout issue as it is creating all those files while not using the batch API.

**Comment by a8w4** [comment]
@jenlampton Thank you for reviewing my pr - it was my first one! And it won't be my last one - I plan to contribute more to backdrop CMS, because I am really hooked (pun intended) since using backdrop CMS for my last two smallish projects, for which Drupal 8/9 would definitely have been overkill: 
https://wir-himmelsthuerer.de/ and
https://www.wir-ochtersumer.de/

**Comment by olafgrabienski** [comment]
>> I've also marked this issue as a feature request since I don't believe it is a bug per se;

> Sorry, I really have to disagree about this issue not being a bug report

Oh, I realized (a bit late) it was me who labeled the issue as bug, so coming back to it. First off, I added the label before #3 and #4 were split off. While I didn't have a closer look at the color shifting now described in #3, the file directory issue now described in #4 was one reason for classifying the whole issue as bug.

As #4 became a separate issue, I'd like to reconsider my classification. To recap the issue shortly: the module creates image files for each page of a PDF regardless of a configured image field limitation. I see @BWPanda's point that it works as expected "from the users point of view" as long as "user" stands for a person with an editor role who doesn't have to care about file storage questions. If in contrast "user" stands for an admin and/or site owner, things look different. In this case the current behavior (more files stored than necessary) is unexpected and might lead to problems or annoyances. Personally, I don't mind the formal classification (bug or not), but if I'd use the module, I'd be happy about having only necessary files stored.

**Comment by a8w4** [comment]
This issue has now a separate PR: #6

**Comment by olafgrabienski** [comment]
> This issue has now a separate PR: #6

Thanks a lot! I've tested the separate PR, and it works for me: Uploading a PDF created the expected number of images (according to the image field limitation).

**Comment by indigoxela** [comment]
I can confirm that the field cardinality is now respected. In my test I set it to "3" and only 3 images got created in the files directory, although the pdf had a lot more pages.

That avoids wasting resources (disk space and mem/cpu when converting). :+1: 

Be it a feature or a bug or a task... RTBC

**Comment by a8w4** [comment]
This is a breeze of fresh air - thank you!

**Comment by olafgrabienski** [comment]
@a8w4 Are you maybe interested to become a maintainer of the module? (Sadly, @BWPanda stepped back [a while ago](https://github.com/backdrop-contrib/pdf_to_image/commit/2aba5ec16f3048ed5f9558ca2e6f9c5ca6048a06).)

If you're interested, please join the Backdrop Contrib group. See the steps on https://docs.backdropcms.org/documentation/contrib-application-process, have also a look at section "Abandoned Projects" on that page.

**Comment by a8w4** [comment]
Thanks for the invitation - I've just applied for the  Backdrop Contrib group.

**Comment by laryn** [comment]
@a8w4 Is this where you applied? I don't see an issue from you:

 - https://github.com/backdrop-ops/contrib/issues

**Comment by a8w4** [comment]
@laryn Sorry, I might have been distracted & forgot to hit the submit-button:
https://github.com/backdrop-ops/contrib/issues/557
