### ISSUE TITLE
The configured file directory of the image field is not honored!

### ISSUE THREAD

**Issue by a8w4** [BWPanda/pdf_to_image#4]
The configured file directory of the image field is not honored - all created images are saved regardless  in the root of the files directory causing clutter.

**Comment by olafgrabienski** [comment]
Thanks again for this other separate PR about the image file directory. Works perfectly on my test site where I configured the image directory to `pictures/post`. Before applying the PR, the images were saved in the `files` root directory. With the PR, the images have been saved in the configured directory.

**Comment by indigoxela** [comment]
Sorry for the delay, I also tested the PR and it works like a charm.

I tested with and without a subdirectory, both paths are handled correctly. :+1: As the code also looks great, I'm setting this to RTBC.

**Comment by a8w4** [comment]
Thank you for testing!
